from __future__ import annotations
import re

_TASK_ID_PATTERN = re.compile(r"^[0-9a-f]{8}$")


def is_valid_task_id(task_id: str) -> bool:
    """Return True if ``task_id`` is an exact system-generated task id.

    The only accepted shape is 8 lowercase hexadecimal characters, which is
    exactly what ``uuid.uuid4().hex[:8]`` produces.  Anything else -- including
    values with ``/``, ``\\``, ``..``, ``.``, trailing separators or any
    non-hex character -- is rejected so it can never be joined onto a path.
    """
    return isinstance(task_id, str) and bool(_TASK_ID_PATTERN.fullmatch(task_id))


def validate_task_id(task_id: str) -> str:
    """Validate a user-supplied ``task_id`` and return it.

    Raises ``ValueError`` when the id is missing or is not an exact 8-hex
    system-generated id.  Used by every task endpoint / service method so a
    malformed id is rejected *before* it reaches ``_task_dir`` or any lock /
    marker / download path lookup.
    """
    if not isinstance(task_id, str) or not task_id.strip():
        raise ValueError("task_id is required")
    task_id = task_id.strip()
    if not is_valid_task_id(task_id):
        raise ValueError(
            f"Invalid task_id: {task_id!r}. Task ids are 8-character lowercase "
            "hexadecimal values generated by the system."
        )
    return task_id


class TaskCancelledError(RuntimeError):
    pass

