#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CAD Translation Web — Portable EXE Launcher (PyInstaller 入口).

该文件由 PyInstaller 编译成 `launcher.exe`（onedir 模式）。exe 内嵌了一个
`runtime_payload.zip`，里面包含：

    backend/            FastAPI 后端源码
    frontend/dist/      已构建的前端静态资源
    tools/              运行期工具（如 LibreDWG）

启动时：
1. 定位内嵌的 runtime_payload.zip（位于 PyInstaller 的 _internal 数据目录）。
2. 将其解压到 LocalAppData 下按 payload 哈希隔离的代码缓存，并保证解压互斥。
3. 将解压目录加入 sys.path，设置环境变量后，以内嵌方式调用 uvicorn 启动
   `app.main:app`。
4. 服务健康检查通过后自动打开浏览器访问 http://127.0.0.1:<PORT>/。
5. 用户数据始终留在 LocalAppData；代码缓存可跨进程复用，不在退出时删除。
"""

from __future__ import annotations

import os
import sys
import hashlib
import socket
import threading
import time
import urllib.error
import urllib.request
import webbrowser
import zipfile
from pathlib import Path

# ---------------------------------------------------------------------------
# 常量
# ---------------------------------------------------------------------------
# PyInstaller 冻结环境下的数据目录
_PAYLOAD_DIR = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
_PAYLOAD_ZIP = _PAYLOAD_DIR / "runtime_payload.zip"

# 默认端口：优先读环境变量，其次读后端 .env，最后 8000
_DEFAULT_PORT = 8000
# 服务启动后自动打开浏览器的等待时间（秒）
_BROWSER_DELAY = 1.2
# 服务就绪探测的最大等待时间（秒）
_READY_TIMEOUT = 60
_APP_DATA_NAME = "CAD Translation"


def _env_or(key: str, default: str) -> str:
    """读取环境变量，缺省时返回默认值。"""
    value = os.environ.get(key, "").strip()
    return value if value else default


def _find_free_port(preferred: int) -> int:
    """优先使用 preferred 端口，若被占用则探测一个空闲端口。"""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("127.0.0.1", preferred))
            return preferred
    except OSError:
        pass
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _acquire_lock(lock_file: Path, timeout: float = 30.0) -> int | None:
    """获取锁并返回持有锁的 fd；超时或失败时 fail-closed。"""
    import msvcrt

    lock_file.parent.mkdir(parents=True, exist_ok=True)
    deadline = time.time() + timeout
    while time.time() < deadline:
        fd = -1
        try:
            fd = os.open(str(lock_file), os.O_CREAT | os.O_RDWR)
            if os.path.getsize(lock_file) == 0:
                os.write(fd, b"0")
            os.lseek(fd, 0, os.SEEK_SET)
            msvcrt.locking(fd, msvcrt.LK_NBLCK, 1)
            return fd
        except OSError:
            if fd >= 0:
                os.close(fd)
            time.sleep(0.2)
    return None


def _release_lock(fd: int) -> None:
    import msvcrt

    try:
        os.lseek(fd, 0, os.SEEK_SET)
        msvcrt.locking(fd, msvcrt.LK_UNLCK, 1)
    except OSError:
        pass
    try:
        os.close(fd)
    except OSError:
        pass


def _extract_payload(dest: Path) -> None:
    """将内嵌的 runtime_payload.zip 解压到 dest。"""
    if not _PAYLOAD_ZIP.exists():
        raise FileNotFoundError(
            f"runtime_payload.zip 未找到（期望位于 {_PAYLOAD_ZIP}）。"
        )
    dest.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(str(_PAYLOAD_ZIP), "r") as zf:
        root = dest.resolve()
        for info in zf.infolist():
            member = Path(info.filename)
            target = (dest / member).resolve()
            if member.is_absolute() or ".." in member.parts:
                raise ValueError(f"unsafe payload member: {info.filename}")
            if root not in target.parents and target != root:
                raise ValueError(f"unsafe payload member: {info.filename}")
            if info.is_dir():
                target.mkdir(parents=True, exist_ok=True)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            with zf.open(info, "r") as source, target.open("wb") as output:
                output.write(source.read())


def _write_env_file(env_path: Path, port: int, data_dir: Path) -> None:
    """写一份最小化的后端 .env，固定单机本地运行所需的开关。"""
    lines = [
        "# Generated by CAD Translation Portable EXE launcher",
        "APP_ENV=production",
        "DEBUG=false",
        f"PORT={port}",
        "HOST=127.0.0.1",
        "ASYNC_TASKS_MODE=local",
        # 便携 exe 只绑定 127.0.0.1，属可信单用户部署，关闭管理员防护，
        # 否则默认 fail-closed 会让所有受保护接口返回 503。
        "ENABLE_ADMIN_GUARD=false",
        f"DATABASE_URL=sqlite:///{(data_dir / 'cad_translation.db').as_posix()}",
        f"UPLOAD_DIR={(data_dir / 'uploads').as_posix()}",
        f"OUTPUT_DIR={(data_dir / 'outputs').as_posix()}",
        f"TEMP_DIR={(data_dir / 'temp').as_posix()}",
    ]
    try:
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"cannot write runtime environment: {env_path}") from exc


def _payload_hash() -> str:
    if not _PAYLOAD_ZIP.is_file():
        raise FileNotFoundError(f"runtime_payload.zip not found: {_PAYLOAD_ZIP}")
    digest = hashlib.sha256()
    with _PAYLOAD_ZIP.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _runtime_paths(payload_hash: str) -> tuple[Path, Path, Path]:
    configured = os.environ.get("LOCALAPPDATA", "").strip()
    local_app_data = Path(configured).expanduser() if configured else Path()
    if not configured:
        local_app_data = Path.home() / "AppData" / "Local"
    app_root = local_app_data / _APP_DATA_NAME
    code_root = app_root / "code-cache" / payload_hash
    data_root = app_root / "data"
    lock_file = app_root / "code-cache" / f"{payload_hash}.lock"
    return code_root, data_root, lock_file


def _wait_for_server(port: int, timeout: float = _READY_TIMEOUT) -> bool:
    """Wait for the local HTTP service before opening a browser."""
    deadline = time.time() + timeout
    url = f"http://127.0.0.1:{port}/"
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2) as response:
                if 200 <= response.status < 500:
                    return True
        except (OSError, urllib.error.URLError):
            time.sleep(0.25)
    return False


def _run_uvicorn(app_dir: Path, port: int) -> None:
    """在 app_dir 上下文中启动 uvicorn（阻塞直到进程退出）。"""
    import uvicorn

    os.chdir(str(app_dir))
    sys.path.insert(0, str(app_dir))

    # 环境变量以显式设置优先；未设置的再交给后端 .env 读取
    os.environ.setdefault("APP_ENV", "production")
    os.environ.setdefault("DEBUG", "false")
    os.environ.setdefault("HOST", "127.0.0.1")
    os.environ.setdefault("PORT", str(port))
    os.environ.setdefault("ASYNC_TASKS_MODE", "local")
    os.environ.setdefault("ENABLE_ADMIN_GUARD", "false")

    uvicorn.run(
        "app.main:app",
        host="127.0.0.1",
        port=port,
        reload=False,
        log_level="info",
        access_log=True,
    )


def main() -> int:
    # ------------------------------------------------------------------
    # 1. 确定按 payload 哈希隔离的 LocalAppData 代码缓存目录
    # ------------------------------------------------------------------
    try:
        payload_hash = _payload_hash()
        root_dir, data_dir, lock_file = _runtime_paths(payload_hash)
    except (OSError, ValueError) as exc:
        print(f"[CAD] runtime payload unavailable: {exc}")
        return 1
    lock_fd: int | None = None

    def cache_ready() -> bool:
        marker = root_dir / ".payload-ready"
        return (
            marker.is_file()
            and marker.read_text(encoding="ascii") == payload_hash
            and (root_dir / "backend/app/main.py").is_file()
            and (root_dir / "frontend/dist/index.html").is_file()
        )

    needs_extract = not cache_ready()

    if needs_extract:
        lock_fd = _acquire_lock(lock_file)
        if lock_fd is None:
            print("[CAD] another instance is preparing the runtime; timed out safely")
            return 1
        try:
            if not cache_ready():
                staging = root_dir.parent / f".{root_dir.name}.staging-{os.getpid()}"
                if staging.exists():
                    import shutil

                    shutil.rmtree(staging)
                _extract_payload(staging)
                for required in ("backend/app/main.py", "frontend/dist/index.html"):
                    if not (staging / required).is_file():
                        raise FileNotFoundError(f"payload is missing {required}")
                (staging / ".payload-ready").write_text(payload_hash, encoding="ascii")
                root_dir.parent.mkdir(parents=True, exist_ok=True)
                if root_dir.exists():
                    stale = root_dir.with_name(f"{root_dir.name}.stale-{os.getpid()}")
                    os.replace(root_dir, stale)
                os.replace(staging, root_dir)
        except Exception as exc:  # noqa: BLE001 - 启动失败时给出可读提示
            print(f"[CAD] 解压运行负载失败: {exc}")
            return 1
        finally:
            _release_lock(lock_fd)
            lock_fd = None
    # ------------------------------------------------------------------
    # 2. 挑选可用端口并写入最小 .env
    # ------------------------------------------------------------------
    try:
        preferred = int(_env_or("CAD_PORT", str(_DEFAULT_PORT)))
        port = _find_free_port(preferred)
        backend_dir = root_dir / "backend"
        data_dir.mkdir(parents=True, exist_ok=True)
        env_path = data_dir / f".runtime-{os.getpid()}-{port}.env"
        _write_env_file(env_path, port, data_dir)
    except (OSError, RuntimeError, ValueError) as exc:
        if lock_fd is not None:
            _release_lock(lock_fd)
        print(f"[CAD] runtime setup failed: {exc}")
        return 1
    os.environ["CAD_TRANSLATION_ENV_FILE"] = str(env_path)
    # Runtime config is resolved from os.environ before Settings reads .env.
    os.environ["CAD_TRANSLATION_RUNTIME_CONFIG_FILE"] = str(data_dir / "config/config.json")

    print("=" * 60)
    print("CAD Translation Web (Portable)")
    print("=" * 60)
    print(f"Payload : {_PAYLOAD_ZIP}")
    print(f"Runtime : {root_dir}")
    print(f"Server  : http://127.0.0.1:{port}")
    print(f"Docs    : http://127.0.0.1:{port}/api/docs")
    print("关闭本窗口即可退出。")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 3. 后台线程延迟打开浏览器
    # ------------------------------------------------------------------
    def _open_browser() -> None:
        if _env_or("CAD_HEADLESS", "").lower() in {"1", "true", "yes"}:
            return
        time.sleep(_BROWSER_DELAY)
        if _wait_for_server(port):
            webbrowser.open(f"http://127.0.0.1:{port}")
        else:
            print("[CAD] local service did not become healthy; browser not opened")

    threading.Thread(target=_open_browser, daemon=True).start()

    # ------------------------------------------------------------------
    # 4. 启动后端（阻塞）
    # ------------------------------------------------------------------
    try:
        _run_uvicorn(backend_dir, port)
    finally:
        if lock_fd is not None:
            _release_lock(lock_fd)
        env_path.unlink(missing_ok=True)
        # Code cache and user data are durable. Never delete a shared root on exit.
    return 0


if __name__ == "__main__":
    sys.exit(main())
