#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CAD Translation Web — Portable EXE Launcher (PyInstaller 入口).

该文件由 PyInstaller 编译成 `launcher.exe`（onedir 模式）。exe 内嵌了一个
`runtime_payload.zip`，里面包含：

    backend/            FastAPI 后端源码
    frontend/dist/      已构建的前端静态资源
    tools/              运行期工具（如 LibreDWG）

启动时：
1. 定位内嵌的 runtime_payload.zip（位于 PyInstaller 的 _internal 数据目录）。
2. 将其解压到 %TEMP% 下的独立目录，并保证解压互斥（多实例并发时先争锁）。
3. 将解压目录加入 sys.path，设置环境变量后，以内嵌方式调用 uvicorn 启动
   `app.main:app`。
4. 延迟 1.2s 自动打开浏览器访问 http://127.0.0.1:<PORT>/。
5. 进程退出前清理临时解压目录（可配置保留用于排查）。
"""

from __future__ import annotations

import os
import sys
import json
import shutil
import socket
import tempfile
import threading
import time
import webbrowser
import zipfile
from pathlib import Path

# ---------------------------------------------------------------------------
# 常量
# ---------------------------------------------------------------------------
# PyInstaller 冻结环境下的数据目录
_PAYLOAD_DIR = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
_PAYLOAD_ZIP = _PAYLOAD_DIR / "runtime_payload.zip"

# 默认端口：优先读环境变量，其次读后端 .env，最后 8000
_DEFAULT_PORT = 8000
# 服务启动后自动打开浏览器的等待时间（秒）
_BROWSER_DELAY = 1.2
# 服务就绪探测的最大等待时间（秒）
_READY_TIMEOUT = 60


def _env_or(key: str, default: str) -> str:
    """读取环境变量，缺省时返回默认值。"""
    value = os.environ.get(key, "").strip()
    return value if value else default


def _find_free_port(preferred: int) -> int:
    """优先使用 preferred 端口，若被占用则探测一个空闲端口。"""
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("127.0.0.1", preferred))
            return preferred
    except OSError:
        pass
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _acquire_lock(lock_file: Path, timeout: float = 30.0) -> bool:
    """尝试获取一个跨进程排他锁（仅用于协调解压，避免并发实例互相覆盖）。"""
    import msvcrt

    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            fd = os.open(str(lock_file), os.O_CREAT | os.O_RDWR)
            msvcrt.locking(fd, msvcrt.LK_NBLCK, 1)
            return True
        except OSError:
            try:
                os.close(fd)
            except OSError:
                pass
            time.sleep(0.2)
    return False


def _release_lock(fd: int) -> None:
    import msvcrt

    try:
        os.lseek(fd, 0, os.SEEK_SET)
        msvcrt.locking(fd, msvcrt.LK_UNLCK, 1)
    except OSError:
        pass
    try:
        os.close(fd)
    except OSError:
        pass


def _extract_payload(dest: Path) -> None:
    """将内嵌的 runtime_payload.zip 解压到 dest。"""
    if not _PAYLOAD_ZIP.exists():
        raise FileNotFoundError(
            f"runtime_payload.zip 未找到（期望位于 {_PAYLOAD_ZIP}）。"
        )
    dest.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(str(_PAYLOAD_ZIP), "r") as zf:
        zf.extractall(str(dest))


def _write_env_file(env_path: Path, port: int) -> None:
    """写一份最小化的后端 .env，固定单机本地运行所需的开关。"""
    lines = [
        "# Generated by CAD Translation Portable EXE launcher",
        "APP_ENV=production",
        "DEBUG=false",
        f"PORT={port}",
        "HOST=127.0.0.1",
        "ASYNC_TASKS_MODE=local",
        # 便携 exe 只绑定 127.0.0.1，属可信单用户部署，关闭管理员防护，
        # 否则默认 fail-closed 会让所有受保护接口返回 503。
        "ENABLE_ADMIN_GUARD=false",
    ]
    try:
        env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    except OSError:
        pass


def _run_uvicorn(app_dir: Path, port: int) -> None:
    """在 app_dir 上下文中启动 uvicorn（阻塞直到进程退出）。"""
    import uvicorn

    os.chdir(str(app_dir))
    sys.path.insert(0, str(app_dir))

    # 环境变量以显式设置优先；未设置的再交给后端 .env 读取
    os.environ.setdefault("APP_ENV", "production")
    os.environ.setdefault("DEBUG", "false")
    os.environ.setdefault("HOST", "127.0.0.1")
    os.environ.setdefault("PORT", str(port))
    os.environ.setdefault("ASYNC_TASKS_MODE", "local")
    os.environ.setdefault("ENABLE_ADMIN_GUARD", "false")

    uvicorn.run(
        "app.main:app",
        host="127.0.0.1",
        port=port,
        reload=False,
        log_level="info",
        access_log=True,
    )


def main() -> int:
    # ------------------------------------------------------------------
    # 1. 确定运行时目录（%TEMP%/<basename>），带版本/进程指纹避免冲突
    # ------------------------------------------------------------------
    base_name = _env_or("CAD_TEMP_PREFIX", "cad-translation-web")
    keep_temp = _env_or("CAD_KEEP_TEMP", "").lower() in {"1", "true", "yes"}

    root_dir = Path(tempfile.gettempdir()) / base_name
    lock_fd: int | None = None

    # 若已存在解压目录，先确认关键文件是否齐全；不齐全则重建
    needs_extract = True
    if (root_dir / "backend" / "app" / "main.py").exists():
        needs_extract = False

    lock_file = root_dir.parent / f"{base_name}.lock"
    if needs_extract:
        if root_dir.exists():
            shutil.rmtree(root_dir, ignore_errors=True)
        root_dir.mkdir(parents=True, exist_ok=True)
        if _acquire_lock(lock_file):
            lock_fd = os.open(str(lock_file), os.O_RDWR)
        try:
            _extract_payload(root_dir)
        except Exception as exc:  # noqa: BLE001 - 启动失败时给出可读提示
            print(f"[CAD] 解压运行负载失败: {exc}")
            return 1

    # ------------------------------------------------------------------
    # 2. 挑选可用端口并写入最小 .env
    # ------------------------------------------------------------------
    preferred = int(_env_or("CAD_PORT", str(_DEFAULT_PORT)))
    port = _find_free_port(preferred)
    backend_dir = root_dir / "backend"
    _write_env_file(backend_dir / ".env", port)

    print("=" * 60)
    print("CAD Translation Web (Portable)")
    print("=" * 60)
    print(f"Payload : {_PAYLOAD_ZIP}")
    print(f"Runtime : {root_dir}")
    print(f"Server  : http://127.0.0.1:{port}")
    print(f"Docs    : http://127.0.0.1:{port}/api/docs")
    print("关闭本窗口即可退出。")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 3. 后台线程延迟打开浏览器
    # ------------------------------------------------------------------
    def _open_browser() -> None:
        time.sleep(_BROWSER_DELAY)
        webbrowser.open(f"http://127.0.0.1:{port}")

    threading.Thread(target=_open_browser, daemon=True).start()

    # ------------------------------------------------------------------
    # 4. 启动后端（阻塞）
    # ------------------------------------------------------------------
    try:
        _run_uvicorn(backend_dir, port)
    finally:
        if lock_fd is not None:
            _release_lock(lock_fd)
        if not keep_temp:
            shutil.rmtree(root_dir, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
